name: Download File to Repository

on:
  workflow_dispatch:  # این اجازه می‌دهد که به صورت دستی اجرا شود

jobs:
  download-file:
    runs-on: ubuntu-latest

    env:
      FILE_URL: https://github.com/D1menc1a/dnstt-android-proxy/releases/download/v1.0.0-doh/dnstt.apk
      FILE_NAME: dnstt.apk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create files directory if not exists
        run: mkdir -p files

      - name: Download file
        run: |
          curl -L $FILE_URL -o files/$FILE_NAME

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add files/$FILE_NAME
          git commit -m "Download file $FILE_NAME from $FILE_URL" || echo "No changes to commit"
          git push || echo "Failed to push changes"